# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'ExampleApp' do

  pod 'PNChartSwift', :path => "../"

end

target 'ExampleAppTests' do

end

